[parameters]
device = "cuda"
num_epochs = 20
model = "ResNet50"
model_name = ""
rescale_w = 224
rescale_h = 224
batch_size = 8 # doesn't do anything, is defaulted to 8 in parser.py
num_workers = 4


[implemented]
models = [
    "ResNet50", 
    "test", 
    "ViT-pretrained", 
    "ResNet50-untrained", 
    "dummy"
]
