[parameters]
device = "cuda"
num_epochs = 51
model = "ViT-pretrained"
model_name = ""
rescale_w = 224
rescale_h = 224
batch_size = 8
num_workers = 4


[implemented]
models = [
    "ResNet50", "test", "ViT-pretrained", "ResNet50-untrained"
]
