#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=Train
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=output/%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/Medical-Imaging/
source activate ai

cp $HOME/Medical-Imaging/data/dev_labels.csv $TMPDIR
cp -R $HOME/Medical-Imaging/data/cfp $TMPDIR
python main.py --data_dir $TMPDIR --logging
